version: "3.3"

services:
    database:
        image: mariadb:10.1
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        restart: always
        networks:
            - backend
    wordpress:
        build:
            context: .
            dockerfile: ./wordpress/Dockerfile
        volumes:
            - ./src/:/var/www/html
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        depends_on:
            - database
        restart: always
        networks:
            - frontend
            - backend
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
            - ./src/:/var/www/html
        depends_on:
            - wordpress
        restart: always
        networks:
            - frontend
    buildchain:
        build:
            context: .
            dockerfile: ./buildchain/Dockerfile
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - ./src/wp-content/themes/timber-starter-theme/:/project
        depends_on:
            - nginx
        network_mode: "host"

networks:
    frontend:
    backend:
